name: general_json_rpc
description: >-
  This package implements json-rpc v2.0 across any protocol.
  It is intended to be used as a general-purpose json-rpc implementation.

version: 1.1.1
repository: https://github.com/Davenchy/general_json_rpc.git

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  event_object: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
